# Generated by Django 5.0.4 on 2024-04-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('standard', models.CharField(max_length=100)),
                ('goal', models.CharField(max_length=100)),
            ],
        ),
    ]
